<a href="https://colab.research.google.com/github/hasnainaliasghar/ai-journey/blob/main/08%20Pytorch/Traing%20Pipeline%20BreastCancer/PytorchTrainingPipline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Training PipeLine on Breast Cancer DataSet

## Basic Imports

In [1]:
import pandas as pd
import numpy as np

import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
df.shape

(569, 31)

## train_test_split

In [5]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["diagnosis"]),df["diagnosis"],test_size=0.2)

In [8]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 2.91441234,  0.24622729,  3.09982457, ...,  1.6589009 ,
         0.5311518 , -0.2191187 ],
       [-0.42129236, -0.02316977, -0.39019724, ..., -0.32414299,
        -1.2014875 , -0.66035037],
       [ 3.33672568, -0.40700098,  3.43110334, ...,  2.42120608,
         1.26764153,  0.21405149],
       ...,
       [ 0.4889641 ,  0.25814751,  0.46615837, ...,  0.50493893,
         1.74447141,  1.19486488],
       [-0.77797593, -0.03032191, -0.80926488, ..., -0.6698814 ,
        -0.76242631, -0.95432567],
       [-0.73802737,  0.42979874, -0.72603109, ..., -0.7950315 ,
        -0.19274836,  0.23339904]])

In [9]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [11]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

## Numpy to Tensors

In [24]:
# Converting train/test array to tensors
X_train_tensor = torch.from_numpy(X_train.astype(np.float64))
X_test_tensor = torch.from_numpy(X_test.astype(np.float64))
y_train_tensor = torch.from_numpy(y_train.astype(np.float64))
y_test_tensor = torch.from_numpy(y_test.astype(np.float64))

In [25]:
X_test_tensor.shape

torch.Size([114, 30])

## Defining the Model

In [30]:
class NurelNetwork:
  def __init__(self,x):
    self.weights = torch.randn(x.shape[1],1,dtype= torch.float64, requires_grad=True, device=device)
    self.bias = torch.zeros(1,dtype= torch.float64, requires_grad=True, device=device)

  def forward(self,x):
    z = torch.matmul(x,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

## Important Parameters

In [44]:
learning_rate = 0.1
epochs = 25
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')

Using device: cuda

## Training Pipeline

In [45]:
#create model
model = NurelNetwork(X_train_tensor)
model.weights

#forward Pass
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  #Loss Calculation
  loss = model.loss_function(y_pred,y_train_tensor)

  #BackwardPass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
    model.weights.grad.zero_()
    model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.9696414783484295
Epoch: 2, Loss: 1.847353441647241
Epoch: 3, Loss: 1.7372990407755633
Epoch: 4, Loss: 1.6396247849415793
Epoch: 5, Loss: 1.5543543178853063
Epoch: 6, Loss: 1.4811363410576843
Epoch: 7, Loss: 1.4192296874194836
Epoch: 8, Loss: 1.366968900786982
Epoch: 9, Loss: 1.3232754395490158
Epoch: 10, Loss: 1.2874968145507222
Epoch: 11, Loss: 1.2580800079474828
Epoch: 12, Loss: 1.2336242690314017
Epoch: 13, Loss: 1.2129692579567373
Epoch: 14, Loss: 1.1952070777871133
Epoch: 15, Loss: 1.1796501231252485
Epoch: 16, Loss: 1.1657189477145196
Epoch: 17, Loss: 1.1527730032734345
Epoch: 18, Loss: 1.140901862942533
Epoch: 19, Loss: 1.1298240411850773
Epoch: 20, Loss: 1.1191450574007364
Epoch: 21, Loss: 1.1090900162072903
Epoch: 22, Loss: 1.099560394429942
Epoch: 23, Loss: 1.0904822490756323
Epoch: 24, Loss: 1.0817996575950397
Epoch: 25, Loss: 1.0734698795783721

In [46]:
model.bias

tensor([-0.2609], dtype=torch.float64, requires_grad=True)

# Evaluation

In [47]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5147737860679626